# Generated by Django 6.1 on 2026-09-27 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor total')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mesas.mesa', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item_snapshot', models.CharField(max_length=150, verbose_name='nome do item no momento da criação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='subtotal')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em preparo', 'Em preparo'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='status')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='cardapio.item', verbose_name='item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('mesa',), name='unique_open_pedido_per_mesa'),
        ),
    ]
