# Generated by Django 6.1 on 2026-09-27 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100, unique=True, verbose_name='nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=150, verbose_name='nome do item')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='cardapio.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Item do cardápio',
                'verbose_name_plural': 'Itens do cardápio',
            },
        ),
    ]
